--# assume global class CUSTOM_LORDS_MODEL

--# type global CUSTOM_LORDS_EVENT = 
--# "LORD_TYPES_CHANGE" | "SELECTED_LORD_TYPE_CHANGE" | "SKILL_SETS_CHANGE" | "SELECTED_SKILL_SET_CHANGE" | "AVAILABLE_TRAITS_CHANGE" | "SELECTED_TRAITS_CHANGE"