--# assume global class CUSTOM_LORDS_MODEL
--# assume global class CUSTOM_LORDS_ATTRIBUTE_PANEL
--# assume global class CUSTOM_LORDS_TRAIT_FRAME
--# assume global class CUSTOM_LORDS_ART_PANEL

--# type global CUSTOM_LORDS_EVENT = 
--# "LORD_TYPES_CHANGE" | "SELECTED_LORD_TYPE_CHANGE" | "SKILL_SETS_CHANGE" | 
--# "SELECTED_SKILL_SET_CHANGE" | "AVAILABLE_TRAITS_CHANGE" | "SELECTED_TRAITS_CHANGE" |
--# "ATTRIBUTE_VALUE_CHANGE" | "SELECTED_ART_ID_VALUE_CHANGE"