faction_lord_types = {
    SCHEMA = {"key", "faction_type", "lord_type", "lord_type_name"},
    KEY = {"key", "LIST"},
    DATA = {
        {"wh_main_sc_brt_bretonnia", "SUBCULTURE", "dlc07_brt_prophetess_beasts", "Prophetess (Beasts)"},
        {"wh_main_sc_brt_bretonnia", "SUBCULTURE", "dlc07_brt_prophetess_heavens", "Prophetess (Heavens)"},
        {"wh_main_sc_brt_bretonnia", "SUBCULTURE", "dlc07_brt_prophetess_life", "Prophetess (Life)"},
        {"wh_main_sc_brt_bretonnia", "SUBCULTURE", "brt_lord", "Lord"},

        {"wh_main_sc_chs_chaos", "SUBCULTURE", "chs_lord", "Chaos Lord"},
        {"wh_main_sc_chs_chaos", "SUBCULTURE", "chs_sorcerer_lord_death", "Chaos Sorcerer Lord (Death)"},
        {"wh_main_sc_chs_chaos", "SUBCULTURE", "chs_sorcerer_lord_fire", "Chaos Sorcerer Lord (Fire)"},
        {"wh_main_sc_chs_chaos", "SUBCULTURE", "chs_sorcerer_lord_metal", "Chaos Sorcerer Lord (Metal)"},
        {"wh_main_sc_chs_chaos", "SUBCULTURE", "dlc07_chs_sorcerer_lord_shadow", "Chaos Sorcerer Lord (Shadows)"},

        {"wh_dlc03_sc_bst_beastmen", "SUBCULTURE", "dlc03_bst_beastlord", "Beastlord"},

        {"wh_dlc05_sc_wef_wood_elves", "SUBCULTURE", "dlc05_wef_ancient_treeman", "Ancient Treeman"},
        {"wh_dlc05_sc_wef_wood_elves", "SUBCULTURE", "dlc05_wef_glade_lord", "Glade Lord (Male)"},
        {"wh_dlc05_sc_wef_wood_elves", "SUBCULTURE", "dlc05_wef_glade_lord_fem", "Glade Lord (Female)"},

        {"wh_main_sc_dwf_dwarfs", "SUBCULTURE", "dwf_lord", "Lord"},
        {"wh_main_sc_dwf_dwarfs", "SUBCULTURE", "dlc06_dwf_runelord", "Runelord"},

        {"wh_main_sc_grn_greenskins", "SUBCULTURE", "dlc06_grn_night_goblin_warboss", "Night Goblin Warboss"},
        {"wh_main_sc_grn_greenskins", "SUBCULTURE", "grn_goblin_great_shaman", "Goblin Great Shaman"},
        {"wh_main_sc_grn_greenskins", "SUBCULTURE", "grn_orc_warboss", "Orc Warboss"},

        {"wh_main_sc_grn_savage_orcs", "SUBCULTURE", "dlc06_grn_night_goblin_warboss", "Night Goblin Warboss"},
        {"wh_main_sc_grn_savage_orcs", "SUBCULTURE", "grn_goblin_great_shaman", "Goblin Great Shaman"},
        {"wh_main_sc_grn_savage_orcs", "SUBCULTURE", "grn_orc_warboss", "Orc Warboss"},

        {"wh_main_sc_emp_empire", "SUBCULTURE", "emp_lord", "General of the Empire"},
        {"wh_main_sc_emp_empire", "SUBCULTURE", "dlc04_emp_arch_lector", "Arch Lector"},
        {"wh_main_sc_emp_empire", "SUBCULTURE", "wh2_dlc13_emp_cha_huntsmarshal_0", "Huntsman General"},

        {"wh_main_sc_ksl_kislev", "SUBCULTURE", "ksl_lord", "Lord"},

        {"wh_main_sc_nor_norsca", "SUBCULTURE", "nor_marauder_chieftain", "Marauder Chieftain"},

        {"wh_main_sc_teb_teb", "SUBCULTURE", "teb_lord", "Lord"},

        {"wh_main_sc_vmp_vampire_counts", "SUBCULTURE", "vmp_lord", "Vampire Lord"},
        {"wh_main_sc_vmp_vampire_counts", "SUBCULTURE", "vmp_master_necromancer", "Master Necromancer"},
        {"wh_main_sc_vmp_vampire_counts", "SUBCULTURE", "dlc04_vmp_strigoi_ghoul_king", "Strigoi Ghoul King"},

        {"wh2_dlc09_sc_tmb_tomb_kings", "SUBCULTURE", "wh2_dlc09_tmb_tomb_king", "Tomb King"},

        {"wh2_main_sc_def_dark_elves", "SUBCULTURE", "wh2_main_def_dreadlord", "Dreadlord (Sword & Crossbow)"},
        {"wh2_main_sc_def_dark_elves", "SUBCULTURE", "wh2_main_def_dreadlord_fem", "Dreadlord (Sword & Shield)"},
        {"wh2_main_sc_def_dark_elves", "SUBCULTURE", "wh2_dlc10_def_supreme_sorceress_beasts", "Supreme Sorceress (Beasts)"},
        {"wh2_main_sc_def_dark_elves", "SUBCULTURE", "wh2_dlc10_def_supreme_sorceress_dark", "Supreme Sorceress (Dark)"},
        {"wh2_main_sc_def_dark_elves", "SUBCULTURE", "wh2_dlc10_def_supreme_sorceress_death", "Supreme Sorceress (Death)"},
        {"wh2_main_sc_def_dark_elves", "SUBCULTURE", "wh2_dlc10_def_supreme_sorceress_fire", "Supreme Sorceress (Fire)"},
        {"wh2_main_sc_def_dark_elves", "SUBCULTURE", "wh2_dlc10_def_supreme_sorceress_shadow", "Supreme Sorceress (Shadows)"},
        {"wh2_main_sc_def_dark_elves", "SUBCULTURE", "wh2_dlc14_def_high_beastmaster", "High Beastmaster"},

        {"wh2_main_sc_hef_high_elves", "SUBCULTURE", "wh2_main_hef_prince", "Prince"},
        {"wh2_main_sc_hef_high_elves", "SUBCULTURE", "wh2_main_hef_princess", "Princess"},

        {"wh2_main_sc_lzd_lizardmen", "SUBCULTURE", "wh2_main_lzd_saurus_old_blood", "Saurus Oldblood"},
        {"wh2_main_sc_lzd_lizardmen", "SUBCULTURE", "wh2_main_lzd_slann_mage_priest", "Slann Mage-Priest"},
        {"wh2_main_sc_lzd_lizardmen", "SUBCULTURE", "wh2_dlc12_lzd_red_crested_skink_chief", "Red Crested Skink Chief"},

        {"wh2_main_sc_skv_skaven", "SUBCULTURE", "wh2_main_skv_grey_seer_plague", "Grey Seer (Plague)"},
        {"wh2_main_sc_skv_skaven", "SUBCULTURE", "wh2_main_skv_grey_seer_ruin", "Grey Seer (Ruin)"},
        {"wh2_main_sc_skv_skaven", "SUBCULTURE", "wh2_main_skv_warlord", "Warlord"},
        {"wh2_main_sc_skv_skaven", "SUBCULTURE", "wh2_dlc12_skv_warlock_master", "Warlock Master"},
        {"wh2_main_sc_skv_skaven", "SUBCULTURE", "wh2_dlc14_skv_master_assassin", "Master Assassin"},

        {"wh2_dlc11_sc_cst_vampire_coast", "SUBCULTURE", "wh2_dlc11_cst_admiral", "Vampire Fleet Admiral (Vampires)"},
        {"wh2_dlc11_sc_cst_vampire_coast", "SUBCULTURE", "wh2_dlc11_cst_admiral_death", "Vampire Fleet Admiral (Death)"},
        {"wh2_dlc11_sc_cst_vampire_coast", "SUBCULTURE", "wh2_dlc11_cst_admiral_deep", "Vampire Fleet Admiral (Deeps)"},
        {"wh2_dlc11_sc_cst_vampire_coast", "SUBCULTURE", "wh2_dlc11_cst_admiral_fem", "Vampire Fleet Admiral (Vampires) (Female)"},
        {"wh2_dlc11_sc_cst_vampire_coast", "SUBCULTURE", "wh2_dlc11_cst_admiral_fem_death", "Vampire Fleet Admiral (Death) (Female)"},
        {"wh2_dlc11_sc_cst_vampire_coast", "SUBCULTURE", "wh2_dlc11_cst_admiral_fem_deep", "Vampire Fleet Admiral (Deeps) (Female)"}
    }
}

lord_types = {
    SCHEMA = {"key", "skill_set", "skill_set_name", "default_skill_set"},
    KEY = {"key", "LIST"},
    DATA = {
        {"wh2_main_hef_prince", "wh2_main_trait_hef_prince_melee", "Melee", "TRUE"},
        {"wh2_main_hef_prince", "wh2_main_trait_hef_prince_magic", "Magic", "FALSE"},
        {"wh2_main_hef_princess", "wh2_main_trait_hef_princess_ranged", "Ranged", "TRUE"},
        {"wh2_main_hef_princess", "wh2_main_trait_hef_princess_magic", "Magic", "FALSE"}
    }
}

skill_set_skills = {
    SCHEMA = {"key", "skill_set_skill"},
    KEY = {"key", "LIST"},
    DATA = {
        {"wh2_main_trait_hef_prince_melee", "wh2_main_skill_hef_combat_graceful_strikes"},
        {"wh2_main_trait_hef_prince_melee", "module_wh2_main_skill_hef_combat_graceful_strikes"},
        {"wh2_main_trait_hef_prince_melee", "wh_main_skill_all_all_self_foe-seeker"},
        {"wh2_main_trait_hef_prince_melee", "module_wh_main_skill_all_all_self_foe-seeker"},
        {"wh2_main_trait_hef_prince_melee", "wh_main_skill_all_all_self_deadly_onslaught"},
        {"wh2_main_trait_hef_prince_magic", "wh2_main_skill_all_magic_high_02_apotheosis"},
        {"wh2_main_trait_hef_prince_magic", "module_wh2_main_skill_all_magic_high_02_apotheosis"},
        {"wh2_main_trait_hef_prince_magic", "wh_main_skill_all_magic_all_06_evasion"},
        {"wh2_main_trait_hef_prince_magic", "module_wh_main_skill_all_magic_all_06_evasion"},
        {"wh2_main_trait_hef_prince_magic", "wh_main_skill_all_magic_all_11_arcane_conduit"},
        {"wh2_main_trait_hef_princess_ranged", "wh2_main_skill_hef_seeking_arrows"},
        {"wh2_main_trait_hef_princess_ranged", "module_wh2_main_skill_hef_seeking_arrows"},
        {"wh2_main_trait_hef_princess_ranged", "wh_main_skill_all_all_self_foe-seeker"},
        {"wh2_main_trait_hef_princess_ranged", "module_wh_main_skill_all_all_self_foe-seeker"},
        {"wh2_main_trait_hef_princess_ranged", "wh2_main_skill_hef_def_volley_of_arrows"},
        {"wh2_main_trait_hef_princess_magic", "wh2_main_skill_all_magic_high_02_apotheosis"},
        {"wh2_main_trait_hef_princess_magic", "module_wh2_main_skill_all_magic_high_02_apotheosis"},
        {"wh2_main_trait_hef_princess_magic", "wh_main_skill_all_magic_all_06_evasion"},
        {"wh2_main_trait_hef_princess_magic", "module_wh_main_skill_all_magic_all_06_evasion"},
        {"wh2_main_trait_hef_princess_magic", "wh_main_skill_all_magic_all_11_arcane_conduit"}
    }
}

traits = {
    SCHEMA = {"key", "trait_cost"},
    KEY = {"key", "UNIQUE"},
    DATA = {
        {"wh2_main_skill_innate_all_aggressive", "-2"},
        {"wh2_main_skill_innate_all_confident", "-2"},
        {"wh2_main_skill_innate_all_cunning", "-2"},
        {"wh2_main_skill_innate_all_determined", "-2"},
        {"wh2_main_skill_innate_all_disciplined", "-2"},
        {"wh2_main_skill_innate_all_fleet_footed", "-2"},
        {"wh2_main_skill_innate_all_intelligent", "-2"},
        {"wh2_main_skill_innate_all_knowledgeable", "-2"},
        {"wh2_main_skill_innate_all_perceptive", "-2"},
        {"wh2_main_skill_innate_all_strategist", "-2"},
        {"wh2_main_skill_innate_all_strong", "-2"},
        {"wh2_main_skill_innate_all_tactician", "-2"},
        {"wh2_main_skill_innate_all_tough", "-2"},
        {"wh2_main_skill_innate_all_weapon_master", "-2"},
        {"wh2_main_trait_increased_cost_1", "1"},
        {"wh2_main_trait_increased_cost_2", "3"},
        {"wh2_main_trait_increased_cost_3", "5"},
        {"wh2_main_trait_increased_cost_4", "7"},
        {"wh2_main_skill_innate_hef_prince_army_0_fay", "1"},
        {"wh2_main_skill_innate_hef_prince_army_0_ill_prepared", "1"},
        {"wh2_main_skill_innate_hef_prince_battle_0_pale_and_wan", "1"},
        {"wh2_main_skill_innate_hef_prince_battle_0_pigeon_chested", "1"},
        {"wh2_main_skill_innate_hef_prince_battle_0_squishy", "1"},
        {"wh2_main_skill_innate_hef_prince_campaign_0_birdbrained", "1"},
        {"wh2_main_skill_innate_hef_prince_campaign_0_wasteful", "1"},
        {"wh2_main_skill_innate_hef_princess_army_0_indolent", "1"},
        {"wh2_main_skill_innate_hef_princess_army_0_poltroon", "1"},
        {"wh2_main_skill_innate_hef_princess_battle_0_feeble", "1"},
        {"wh2_main_skill_innate_hef_princess_battle_0_inaccurate", "1"},
        {"wh2_main_skill_innate_hef_princess_battle_0_unfortunate", "1"},
        {"wh2_main_skill_innate_hef_princess_campaign_0_dullard", "1"},
        {"wh2_main_skill_innate_hef_prince_army_3_competent", "-2"},
        {"wh2_main_skill_innate_hef_prince_army_3_strong_willed", "-2"},
        {"wh2_main_skill_innate_hef_prince_battle_3_elusive", "-2"},
        {"wh2_main_skill_innate_hef_prince_battle_3_hale_and_hearty", "-2"},
        {"wh2_main_skill_innate_hef_prince_battle_3_trained", "-2"},
        {"wh2_main_skill_innate_hef_prince_campaign_3_observant", "-2"},
        {"wh2_main_skill_innate_hef_prince_campaign_3_unsentimental", "-2"},
        {"wh2_main_skill_innate_hef_princess_army_3_brisk", "-2"},
        {"wh2_main_skill_innate_hef_princess_army_3_resolute", "-2"},
        {"wh2_main_skill_innate_hef_princess_battle_3_accurate", "-2"},
        {"wh2_main_skill_innate_hef_princess_battle_3_fortuitous", "-2"},
        {"wh2_main_skill_innate_hef_princess_battle_3_well_founded", "-2"},
        {"wh2_main_skill_innate_hef_princess_campaign_3_careful", "-2"},
        {"wh2_main_skill_innate_hef_prince_army_7_resistant", "-4"},
        {"wh2_main_skill_innate_hef_prince_battle_7_dangerous", "-4"},
        {"wh2_main_skill_innate_hef_prince_battle_7_resilient", "-4"},
        {"wh2_main_skill_innate_hef_prince_battle_7_vigorous", "-4"},
        {"wh2_main_skill_innate_hef_prince_campaign_7_adept", "-4"},
        {"wh2_main_skill_innate_hef_prince_campaign_7_avaricious", "-4"},
        {"wh2_main_skill_innate_hef_princess_army_7_energetic", "-4"},
        {"wh2_main_skill_innate_hef_princess_battle_7_charmed", "-4"},
        {"wh2_main_skill_innate_hef_princess_battle_7_hawk_eyed", "-4"},
        {"wh2_main_skill_innate_hef_princess_battle_7_strong", "-4"},
        {"wh2_main_skill_innate_hef_princess_campaign_7_vigilant", "-4"},
        -- FACTION SPECIFIC
        {"wh2_main_skill_innate_hef_prince_army_0_scornful", "1"},
        {"wh2_main_skill_innate_hef_prince_campaign_0_disorganised", "1"},
        {"wh2_main_skill_innate_hef_princess_army_0_soft_hearted", "1"},
        {"wh2_main_skill_innate_hef_princess_campaign_0_slovenly", "1"},
        {"wh2_main_skill_innate_hef_princess_campaign_0_tardy", "1"},
        {"wh2_main_skill_innate_hef_prince_army_3_respectful", "-2"},
        {"wh2_main_skill_innate_hef_prince_campaign_3_organised", "-2"},
        {"wh2_main_skill_innate_hef_princess_army_3_retaliatory", "-2"},
        {"wh2_main_skill_innate_hef_princess_campaign_3_example", "-2"},
        {"wh2_main_skill_innate_hef_princess_campaign_3_keen", "-2"},
        {"wh2_main_skill_innate_hef_prince_army_7_doctrinal", "-4"},
        {"wh2_main_skill_innate_hef_prince_army_7_dragon_willed", "-4"},
        {"wh2_main_skill_innate_hef_prince_campaign_7_efficient", "-4"},
        {"wh2_main_skill_innate_hef_princess_army_7_dashing", "-4"},
        {"wh2_main_skill_innate_hef_princess_army_7_punitive", "-4"},
        {"wh2_main_skill_innate_hef_princess_campaign_7_ardent", "-4"},
        {"wh2_main_skill_innate_hef_princess_campaign_7_exemplar", "-4"},
        {"wh2_main_skill_innate_bst_booze_cravings", "-2"},
        {"wh2_main_skill_innate_bst_khornes_fury", "-2"},
        {"wh2_main_skill_innate_bst_nurgles_foul_stink", "-2"},
        {"wh2_main_skill_innate_bst_torment_utterances", "-2"},
        {"wh2_main_skill_innate_bst_unsated_bloodthirst", "-2"},
        {"wh_main_skill_innate_brt_virtue_audacity", "-2"},
        {"wh_main_skill_innate_brt_virtue_confidence", "-2"},
        {"wh_main_skill_innate_brt_virtue_discipline", "-2"},
        {"wh_main_skill_innate_brt_virtue_duty", "-2"},
        {"wh_main_skill_innate_brt_virtue_heroism", "-2"},
        {"wh_main_skill_innate_brt_virtue_ideal", "-2"},
        {"wh_main_skill_innate_brt_virtue_impetuous_knight", "-2"},
        {"wh_main_skill_innate_brt_virtue_joust", "-2"},
        {"wh_main_skill_innate_brt_virtue_knightly_temper", "-2"},
        {"wh_main_skill_innate_brt_virtue_noble_disdain", "-2"},
        {"wh_main_skill_innate_brt_virtue_penitent", "-2"},
        {"wh_main_skill_innate_brt_virtue_stoicism", "-2"},
        {"wh2_main_skill_innate_chs_diabolic_spendour", "-2"},
        {"wh2_main_skill_innate_chs_dominance", "-2"},
        {"wh2_main_skill_innate_def_cruel", "-2"},
        {"wh2_main_skill_innate_def_malevolent", "-2"},
        {"wh2_main_skill_innate_def_malicious", "-2"},
        {"wh2_main_skill_innate_def_spiteful", "-2"},
        {"wh2_main_skill_innate_def_vicious", "-2"},
        {"wh2_main_skill_innate_dwf_ancestral_blood_grimnir", "-2"},
        {"wh2_main_skill_innate_dwf_ancestral_blood_grungni", "-2"},
        {"wh2_main_skill_innate_dwf_ancestral_blood_valaya", "-2"},
        {"wh2_main_skill_innate_grn_big_bully", "-2"},
        {"wh2_main_skill_innate_grn_bragga", "-2"},
        {"wh2_main_skill_innate_grn_mushroom_addicted", "-2"},
        {"wh2_main_skill_innate_grn_serial_danca", "-2"},
        {"wh2_main_skill_innate_grn_tortura", "-2"},
        {"wh2_main_skill_innate_emp_imperious", "-2"},
        {"wh2_main_skill_innate_emp_monster_hunter", "-2"},
        {"wh2_main_skill_innate_emp_monster_tracker", "-2"},
        {"wh2_main_skill_innate_emp_noble", "-2"},
        {"wh2_main_skill_innate_emp_regal", "-2"},
        {"wh2_main_skill_innate_lzd_arrogant", "-2"},
        {"wh2_main_skill_innate_lzd_humble", "-2"},
        {"wh2_main_skill_innate_lzd_pompous", "-2"},
        {"wh2_main_skill_innate_lzd_uncompromising", "-2"},
        {"wh_dlc07_brt_skill_innate_all_honourable", "-2"},
        {"wh_dlc07_brt_skill_innate_all_intelligent", "-2"},
        {"wh_dlc07_brt_skill_innate_all_magnanimous", "-2"},
        {"wh_dlc07_brt_skill_innate_all_melancholic", "-2"},
        {"wh_dlc07_brt_skill_innate_all_phlegmatic", "-2"},
        {"wh_dlc07_brt_skill_innate_all_sanguine", "-2"},
        {"wh_dlc07_brt_skill_innate_all_uncompromising", "-2"},
        {"wh2_main_skill_innate_skv_sharp_claws", "-2"},
        {"wh2_main_skill_innate_skv_sharp_teeth", "-2"},
        {"wh2_main_skill_innate_skv_sneaky", "-2"},
        {"wh2_main_skill_innate_skv_warpstone_hoarder", "-2"},
        {"wh2_dlc09_skill_innate_tmb_eternal", "-2"},
        {"wh2_dlc09_skill_innate_tmb_master_of_ceremony", "-2"},
        {"wh2_dlc09_skill_innate_tmb_prepared", "-2"},
        {"wh2_dlc09_skill_innate_tmb_scavenger", "-2"},
        {"wh2_dlc09_skill_innate_tmb_treacherous", "-2"},
        {"wh2_dlc09_skill_innate_tmb_trustworthy", "-2"},
        {"wh2_dlc09_skill_innate_tmb_wrathful", "-2"},
        {"wh2_main_skill_innate_vmp_dark_majesty", "-2"},
        {"wh2_main_skill_innate_vmp_devious", "-2"},
        {"wh2_main_skill_innate_vmp_dread_incarnate", "-2"},
        {"wh2_main_skill_innate_vmp_lore_keeper", "-2"},
        {"wh2_main_skill_innate_vmp_master_of_the_black_arts", "-2"},
        {"wh2_main_skill_innate_wef_ariels_chosen", "-2"},
        {"wh2_main_skill_innate_wef_talon_of_kurnous", "-2"},
        -- NEW TRAITS
        {"wh2_clc_trait_emp_questionable_excuses", "-2"},
        {"wh2_clc_trait_all_perseverant", "-2"},
        {"wh2_clc_trait_lzd_bloodthirsty", "-2"}
    }
}

trait_scope = {
    SCHEMA = {"key", "trait_scope_type", "trait_scope"},
    KEY = {"key", "LIST"},
    DATA = {
        {"wh2_main_skill_innate_hef_prince_army_0_scornful", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_prince_campaign_0_disorganised", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_army_0_soft_hearted", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_campaign_0_slovenly", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_campaign_0_tardy", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_prince_army_3_respectful", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_prince_campaign_3_organised", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_army_3_retaliatory", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_campaign_3_example", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_campaign_3_keen", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_prince_army_7_doctrinal", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_prince_army_7_dragon_willed", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_prince_campaign_7_efficient", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_army_7_dashing", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_army_7_punitive", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_campaign_7_ardent", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_hef_princess_campaign_7_exemplar", "SUBCULTURE", "wh2_main_sc_hef_high_elves"},
        {"wh2_main_skill_innate_bst_booze_cravings", "SUBCULTURE", "wh_dlc03_sc_bst_beastmen"},
        {"wh2_main_skill_innate_bst_khornes_fury", "SUBCULTURE", "wh_dlc03_sc_bst_beastmen"},
        {"wh2_main_skill_innate_bst_nurgles_foul_stink", "SUBCULTURE", "wh_dlc03_sc_bst_beastmen"},
        {"wh2_main_skill_innate_bst_torment_utterances", "SUBCULTURE", "wh_dlc03_sc_bst_beastmen"},
        {"wh2_main_skill_innate_bst_unsated_bloodthirst", "SUBCULTURE", "wh_dlc03_sc_bst_beastmen"},
        {"wh_main_skill_innate_brt_virtue_audacity", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_confidence", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_discipline", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_duty", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_heroism", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_ideal", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_impetuous_knight", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_joust", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_knightly_temper", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_noble_disdain", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_penitent", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_main_skill_innate_brt_virtue_stoicism", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh2_main_skill_innate_chs_diabolic_spendour", "SUBCULTURE", "wh_main_sc_chs_chaos"},
        {"wh2_main_skill_innate_chs_dominance", "SUBCULTURE", "wh_main_sc_chs_chaos"},
        {"wh2_main_skill_innate_def_cruel", "SUBCULTURE", "wh2_main_sc_def_dark_elves"},
        {"wh2_main_skill_innate_def_malevolent", "SUBCULTURE", "wh2_main_sc_def_dark_elves"},
        {"wh2_main_skill_innate_def_malicious", "SUBCULTURE", "wh2_main_sc_def_dark_elves"},
        {"wh2_main_skill_innate_def_spiteful", "SUBCULTURE", "wh2_main_sc_def_dark_elves"},
        {"wh2_main_skill_innate_def_vicious", "SUBCULTURE", "wh2_main_sc_def_dark_elves"},
        {"wh2_main_skill_innate_dwf_ancestral_blood_grimnir", "SUBCULTURE", "wh_main_sc_dwf_dwarfs"},
        {"wh2_main_skill_innate_dwf_ancestral_blood_grungni", "SUBCULTURE", "wh_main_sc_dwf_dwarfs"},
        {"wh2_main_skill_innate_dwf_ancestral_blood_valaya", "SUBCULTURE", "wh_main_sc_dwf_dwarfs"},
        {"wh2_main_skill_innate_grn_big_bully", "SUBCULTURE", "wh_main_sc_grn_greenskins"},
        {"wh2_main_skill_innate_grn_bragga", "SUBCULTURE", "wh_main_sc_grn_greenskins"},
        {"wh2_main_skill_innate_grn_mushroom_addicted", "SUBCULTURE", "wh_main_sc_grn_greenskins"},
        {"wh2_main_skill_innate_grn_serial_danca", "SUBCULTURE", "wh_main_sc_grn_greenskins"},
        {"wh2_main_skill_innate_grn_tortura", "SUBCULTURE", "wh_main_sc_grn_greenskins"},
        {"wh2_main_skill_innate_grn_big_bully", "SUBCULTURE", "wh_main_sc_grn_savage_orcs"},
        {"wh2_main_skill_innate_grn_bragga", "SUBCULTURE", "wh_main_sc_grn_savage_orcs"},
        {"wh2_main_skill_innate_grn_mushroom_addicted", "SUBCULTURE", "wh_main_sc_grn_savage_orcs"},
        {"wh2_main_skill_innate_grn_serial_danca", "SUBCULTURE", "wh_main_sc_grn_savage_orcs"},
        {"wh2_main_skill_innate_grn_tortura", "SUBCULTURE", "wh_main_sc_grn_savage_orcs"},
        {"wh2_main_skill_innate_emp_imperious", "SUBCULTURE", "wh_main_sc_emp_empire"},
        {"wh2_main_skill_innate_emp_monster_hunter", "SUBCULTURE", "wh_main_sc_emp_empire"},
        {"wh2_main_skill_innate_emp_monster_tracker", "SUBCULTURE", "wh_main_sc_emp_empire"},
        {"wh2_main_skill_innate_emp_noble", "SUBCULTURE", "wh_main_sc_emp_empire"},
        {"wh2_main_skill_innate_emp_regal", "SUBCULTURE", "wh_main_sc_emp_empire"},
        {"wh2_main_skill_innate_lzd_arrogant", "SUBCULTURE", "wh2_main_sc_lzd_lizardmen"},
        {"wh2_main_skill_innate_lzd_humble", "SUBCULTURE", "wh2_main_sc_lzd_lizardmen"},
        {"wh2_main_skill_innate_lzd_pompous", "SUBCULTURE", "wh2_main_sc_lzd_lizardmen"},
        {"wh2_main_skill_innate_lzd_uncompromising", "SUBCULTURE", "wh2_main_sc_lzd_lizardmen"},
        {"wh_dlc07_brt_skill_innate_all_honourable", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_dlc07_brt_skill_innate_all_intelligent", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_dlc07_brt_skill_innate_all_magnanimous", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_dlc07_brt_skill_innate_all_melancholic", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_dlc07_brt_skill_innate_all_phlegmatic", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_dlc07_brt_skill_innate_all_sanguine", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh_dlc07_brt_skill_innate_all_uncompromising", "SUBCULTURE", "wh_main_sc_brt_bretonnia"},
        {"wh2_main_skill_innate_skv_sharp_claws", "SUBCULTURE", "wh2_main_sc_skv_skaven"},
        {"wh2_main_skill_innate_skv_sharp_teeth", "SUBCULTURE", "wh2_main_sc_skv_skaven"},
        {"wh2_main_skill_innate_skv_sneaky", "SUBCULTURE", "wh2_main_sc_skv_skaven"},
        {"wh2_main_skill_innate_skv_warpstone_hoarder", "SUBCULTURE", "wh2_main_sc_skv_skaven"},
        {"wh2_dlc09_skill_innate_tmb_eternal", "SUBCULTURE", "wh2_dlc09_sc_tmb_tomb_kings"},
        {"wh2_dlc09_skill_innate_tmb_master_of_ceremony", "SUBCULTURE", "wh2_dlc09_sc_tmb_tomb_kings"},
        {"wh2_dlc09_skill_innate_tmb_prepared", "SUBCULTURE", "wh2_dlc09_sc_tmb_tomb_kings"},
        {"wh2_dlc09_skill_innate_tmb_scavenger", "SUBCULTURE", "wh2_dlc09_sc_tmb_tomb_kings"},
        {"wh2_dlc09_skill_innate_tmb_treacherous", "SUBCULTURE", "wh2_dlc09_sc_tmb_tomb_kings"},
        {"wh2_dlc09_skill_innate_tmb_trustworthy", "SUBCULTURE", "wh2_dlc09_sc_tmb_tomb_kings"},
        {"wh2_dlc09_skill_innate_tmb_wrathful", "SUBCULTURE", "wh2_dlc09_sc_tmb_tomb_kings"},
        {"wh2_main_skill_innate_vmp_dark_majesty", "SUBCULTURE", "wh_main_sc_vmp_vampire_counts"},
        {"wh2_main_skill_innate_vmp_devious", "SUBCULTURE", "wh_main_sc_vmp_vampire_counts"},
        {"wh2_main_skill_innate_vmp_dread_incarnate", "SUBCULTURE", "wh_main_sc_vmp_vampire_counts"},
        {"wh2_main_skill_innate_vmp_lore_keeper", "SUBCULTURE", "wh_main_sc_vmp_vampire_counts"},
        {"wh2_main_skill_innate_vmp_master_of_the_black_arts", "SUBCULTURE", "wh_main_sc_vmp_vampire_counts"},
        {"wh2_main_skill_innate_wef_ariels_chosen", "SUBCULTURE", "wh_dlc05_sc_wef_wood_elves"},
        {"wh2_main_skill_innate_wef_talon_of_kurnous", "SUBCULTURE", "wh_dlc05_sc_wef_wood_elves"},
        {"wh2_clc_trait_emp_questionable_excuses", "SUBCULTURE", "wh_main_sc_emp_empire"},
        {"wh2_clc_trait_lzd_bloodthirsty", "SUBCULTURE", "wh2_main_sc_lzd_lizardmen"},

        {"wh2_main_skill_innate_hef_princess_battle_3_accurate", "LORD_TYPE", "wh2_main_hef_princess"},
        {"wh2_main_skill_innate_hef_princess_battle_0_inaccurate", "LORD_TYPE", "wh2_main_hef_princess"},
        {"wh2_main_skill_innate_hef_princess_battle_7_hawk_eyed", "LORD_TYPE", "wh2_main_hef_princess"}
    }
}

trait_incidents = {
    SCHEMA = {"key", "incident_key"},
    KEY = {"key", "LIST"},
    DATA = {
        {"wh2_main_trait_increased_cost_1", "wh2_main_incident_treasury_down_1"},
        {"wh2_main_trait_increased_cost_2", "wh2_main_incident_treasury_down_2"},
        {"wh2_main_trait_increased_cost_3", "wh2_main_incident_treasury_down_3"},
        {"wh2_main_trait_increased_cost_4", "wh2_main_incident_treasury_down_4"}
    }
}

attributes = {
    SCHEMA = {"key", "attribute_value", "effect_bundle"},
    KEY = {"key", "LIST"},
    DATA = {
        {"char_melee_attack", "4", "wh2_vanish_clc_attribute_melee_attack_4"},
        {"char_melee_attack", "3", "wh2_vanish_clc_attribute_melee_attack_3"},
        {"char_melee_attack", "2", "wh2_vanish_clc_attribute_melee_attack_2"},
        {"char_melee_attack", "1", "wh2_vanish_clc_attribute_melee_attack_1"},
        {"char_melee_attack", "0", "wh2_vanish_clc_attribute_melee_attack_0"},
        {"char_melee_attack", "-1", "wh2_vanish_clc_attribute_melee_attack_minus_1"},
        {"char_melee_attack", "-2", "wh2_vanish_clc_attribute_melee_attack_minus_2"},
        {"char_melee_attack", "-3", "wh2_vanish_clc_attribute_melee_attack_minus_3"},
        {"char_melee_attack", "-4", "wh2_vanish_clc_attribute_melee_attack_minus_4"},
        {"char_melee_defence", "4", "wh2_vanish_clc_attribute_melee_defence_4"},
        {"char_melee_defence", "3", "wh2_vanish_clc_attribute_melee_defence_3"},
        {"char_melee_defence", "2", "wh2_vanish_clc_attribute_melee_defence_2"},
        {"char_melee_defence", "1", "wh2_vanish_clc_attribute_melee_defence_1"},
        {"char_melee_defence", "0", "wh2_vanish_clc_attribute_melee_defence_0"},
        {"char_melee_defence", "-1", "wh2_vanish_clc_attribute_melee_defence_minus_1"},
        {"char_melee_defence", "-2", "wh2_vanish_clc_attribute_melee_defence_minus_2"},
        {"char_melee_defence", "-3", "wh2_vanish_clc_attribute_melee_defence_minus_3"},
        {"char_melee_defence", "-4", "wh2_vanish_clc_attribute_melee_defence_minus_4"},
        {"char_armour", "4", "wh2_vanish_clc_attribute_armour_4"},
        {"char_armour", "3", "wh2_vanish_clc_attribute_armour_3"},
        {"char_armour", "2", "wh2_vanish_clc_attribute_armour_2"},
        {"char_armour", "1", "wh2_vanish_clc_attribute_armour_1"},
        {"char_armour", "0", "wh2_vanish_clc_attribute_armour_0"},
        {"char_armour", "-1", "wh2_vanish_clc_attribute_armour_minus_1"},
        {"char_armour", "-2", "wh2_vanish_clc_attribute_armour_minus_2"},
        {"char_armour", "-3", "wh2_vanish_clc_attribute_armour_minus_3"},
        {"char_armour", "-4", "wh2_vanish_clc_attribute_armour_minus_4"},
        {"char_weapon_strength", "4", "wh2_vanish_clc_attribute_weapon_strength_4"},
        {"char_weapon_strength", "3", "wh2_vanish_clc_attribute_weapon_strength_3"},
        {"char_weapon_strength", "2", "wh2_vanish_clc_attribute_weapon_strength_2"},
        {"char_weapon_strength", "1", "wh2_vanish_clc_attribute_weapon_strength_1"},
        {"char_weapon_strength", "0", "wh2_vanish_clc_attribute_weapon_strength_0"},
        {"char_weapon_strength", "-1", "wh2_vanish_clc_attribute_weapon_strength_minus_1"},
        {"char_weapon_strength", "-2", "wh2_vanish_clc_attribute_weapon_strength_minus_2"},
        {"char_weapon_strength", "-3", "wh2_vanish_clc_attribute_weapon_strength_minus_3"},
        {"char_weapon_strength", "-4", "wh2_vanish_clc_attribute_weapon_strength_minus_4"},
        {"char_speed", "4", "wh2_vanish_clc_attribute_speed_4"},
        {"char_speed", "3", "wh2_vanish_clc_attribute_speed_3"},
        {"char_speed", "2", "wh2_vanish_clc_attribute_speed_2"},
        {"char_speed", "1", "wh2_vanish_clc_attribute_speed_1"},
        {"char_speed", "0", "wh2_vanish_clc_attribute_speed_0"},
        {"char_speed", "-1", "wh2_vanish_clc_attribute_speed_minus_1"},
        {"char_speed", "-2", "wh2_vanish_clc_attribute_speed_minus_2"},
        {"char_speed", "-3", "wh2_vanish_clc_attribute_speed_minus_3"},
        {"char_speed", "-4", "wh2_vanish_clc_attribute_speed_minus_4"},
        {"char_charge_bonus", "4", "wh2_vanish_clc_attribute_charge_bonus_4"},
        {"char_charge_bonus", "3", "wh2_vanish_clc_attribute_charge_bonus_3"},
        {"char_charge_bonus", "2", "wh2_vanish_clc_attribute_charge_bonus_2"},
        {"char_charge_bonus", "1", "wh2_vanish_clc_attribute_charge_bonus_1"},
        {"char_charge_bonus", "0", "wh2_vanish_clc_attribute_charge_bonus_0"},
        {"char_charge_bonus", "-1", "wh2_vanish_clc_attribute_charge_bonus_minus_1"},
        {"char_charge_bonus", "-2", "wh2_vanish_clc_attribute_charge_bonus_minus_2"},
        {"char_charge_bonus", "-3", "wh2_vanish_clc_attribute_charge_bonus_minus_3"},
        {"char_charge_bonus", "-4", "wh2_vanish_clc_attribute_charge_bonus_minus_4"},
        {"char_winds", "4", "wh2_vanish_clc_attribute_winds_of_magic_4"},
        {"char_winds", "3", "wh2_vanish_clc_attribute_winds_of_magic_3"},
        {"char_winds", "2", "wh2_vanish_clc_attribute_winds_of_magic_2"},
        {"char_winds", "1", "wh2_vanish_clc_attribute_winds_of_magic_1"},
        {"char_winds", "0", "wh2_vanish_clc_attribute_winds_of_magic_0"},
        {"char_winds", "-1", "wh2_vanish_clc_attribute_winds_of_magic_minus_1"},
        {"char_winds", "-2", "wh2_vanish_clc_attribute_winds_of_magic_minus_2"},
        {"char_winds", "-3", "wh2_vanish_clc_attribute_winds_of_magic_minus_3"},
        {"char_winds", "-4", "wh2_vanish_clc_attribute_winds_of_magic_minus_4"}
    }
}

attribute_tooptip = {
    SCHEMA = {"key", "attribute_tooltip"},
    KEY = {"key", "UNIQUE"},
    DATA = {
        {"char_melee_attack", "Melee Attack"},
        {"char_melee_defence", "Melee Defence"},
        {"char_armour", "Armour"},
        {"char_weapon_strength", "Weapon Strength (%)"},
        {"char_speed", "Speed (%)"},
        {"char_charge_bonus", "Charge Bonus"},
        {"char_winds", "Winds of Magic Power Reserve"}
    }
}

dlc_lords = {
    SCHEMA = {"key", "required_dlc"},
    KEY = {"key", "UNIQUE"},
    DATA = {
        {"wh2_dlc10_def_supreme_sorceress_beasts", "TW_WH2_DLC10_QUEEN_CRONE"},
        {"wh2_dlc10_def_supreme_sorceress_dark", "TW_WH2_DLC10_QUEEN_CRONE"},
        {"wh2_dlc10_def_supreme_sorceress_death", "TW_WH2_DLC10_QUEEN_CRONE"},
        {"wh2_dlc10_def_supreme_sorceress_fire", "TW_WH2_DLC10_QUEEN_CRONE"},
        {"wh2_dlc10_def_supreme_sorceress_shadow", "TW_WH2_DLC10_QUEEN_CRONE"},
        
        {"wh2_dlc12_skv_warlock_master", "TW_WH2_DLC12_PROPHET"},
        {"wh2_dlc12_lzd_red_crested_skink_chief", "TW_WH2_DLC12_PROPHET"},
        
        {"wh2_dlc13_emp_cha_huntsmarshal_0", "TW_WH2_DLC13_HUNTER"},
        
        {"wh2_dlc14_def_high_beastmaster", "TW_WH2_DLC14_SHADOW"},
        {"wh2_dlc14_skv_master_assassin", "TW_WH2_DLC14_SHADOW"}
    }
}