trait_level_effects_tables = {
	SCHEMA = {"trait_level", "effect", "effect_scope", "value"},
	KEY = {"trait_level", "LIST"},
	DATA = {
		{"wh2_main_trait_hef_prince_magic", "wh2_main_effect_magic_high_enable_apotheosis", "character_to_character_own", "1"},
		{"wh2_main_skill_innate_all_aggressive", "wh_main_effect_character_stat_mod_charge_add", "character_to_character_own", "8"},
		{"wh2_main_skill_innate_all_aggressive", "wh_main_effect_character_stat_mod_melee_damage", "character_to_character_own", "5"},
		{"wh2_main_skill_innate_all_confident", "wh_main_effect_force_unit_stat_morale", "character_to_force_own", "2"},
		{"wh2_main_skill_innate_all_cunning", "wh_main_effect_character_stat_enable_poison_attacks", "character_to_character_own", "1"},
		{"wh2_main_skill_innate_all_cunning", "wh_main_effect_force_army_campaign_ambush_attack_success_chance", "character_to_force_regionwide_own", "10"},
		{"wh2_main_skill_innate_all_determined", "wh_main_effect_character_stat_mod_morale", "character_to_character_own", "3"},
		{"wh2_main_skill_innate_all_determined", "wh_main_effect_unit_enable_attribute_immune_to_psychology", "character_to_character_own", "1"},
		{"wh2_main_skill_innate_all_disciplined", "wh_main_effect_force_unit_stat_melee_attack", "character_to_force_own", "2"},
		{"wh2_main_skill_innate_all_disciplined", "wh_main_effect_force_unit_stat_morale", "character_to_force_own", "2"},
		{"wh2_main_skill_innate_all_fleet_footed", "wh_main_effect_character_stat_mod_battle_movement_speed", "character_to_character_own", "15"},
		{"wh2_main_skill_innate_all_fleet_footed", "wh_main_effect_unit_enable_attribute_strider", "character_to_character_own", "1"},
		{"wh2_main_skill_innate_all_intelligent", "wh_main_effect_agent_defence_wound_chance_mod", "character_to_character_own", "5"},
		{"wh2_main_skill_innate_all_intelligent", "wh_main_effect_force_army_campaign_ambush_defence_success_chance", "character_to_force_own_unseen", "10"},
		{"wh2_main_skill_innate_all_knowledgeable", "wh_main_effect_military_force_winds_of_magic_depletion_mod_character", "character_to_force_own_factionwide", "5"},
		{"wh2_main_skill_innate_all_knowledgeable", "wh_main_effect_military_force_winds_of_magic_depletion_mod_character_enemy", "general_to_force_enemy_regionwide", "-5"},
		{"wh2_main_skill_innate_all_perceptive", "wh_main_effect_agent_field_line_of_sight_mod", "character_to_character_own", "10"},
		{"wh2_main_skill_innate_all_perceptive", "wh_main_effect_character_mod_ancillary_drop", "character_to_character_own", "15"},
		{"wh2_main_skill_innate_all_strategist", "wh_main_effect_agent_movement_range_mod", "character_to_character_own", "5"},
		{"wh2_main_skill_innate_all_strong", "wh_main_effect_character_stat_mod_armour", "character_to_character_own", "3"},
		{"wh2_main_skill_innate_all_strong", "wh_main_effect_character_stat_mod_melee_attack", "character_to_character_own", "2"},
		{"wh2_main_skill_innate_all_strong", "wh_main_effect_character_stat_mod_melee_damage", "character_to_character_own", "5"},
		{"wh2_main_skill_innate_all_tactician", "wh_main_effect_character_stat_mod_personal_aura_morale_effect", "character_to_character_own", "2"},
		{"wh2_main_skill_innate_all_tactician", "wh_main_effect_character_stat_mod_personal_aura_size", "character_to_character_own", "10"},
		{"wh2_main_skill_innate_all_tough", "wh_main_effect_character_stat_mod_armour", "character_to_character_own", "5"},
		{"wh2_main_skill_innate_all_tough", "wh_main_effect_character_stat_mod_melee_defence", "character_to_character_own", "3"},
		{"wh2_main_skill_innate_all_weapon_master", "wh_main_effect_character_stat_mod_ap_damage", "character_to_character_own", "5"},
		{"wh2_main_skill_innate_all_weapon_master", "wh_main_effect_character_stat_mod_melee_attack", "character_to_character_own", "3"},
		{"wh2_main_trait_increased_cost", "increased_cost", "character_to_character_own", "1000"}
	}
}