faction_lord_types = {
    SCHEMA = {"key", "faction_type", "lord_type", "lord_type_name"},
    KEY = {"key", "LIST"},
    DATA = {
        {"wh_dlc05_sc_wef_wood_elves", "SUBCULTURE", "wef_darkweaver", "Darkweaver"},
        {"wh_dlc05_sc_wef_wood_elves", "SUBCULTURE", "wef_highweaver", "Highweaver"},
        {"wh_dlc05_sc_wef_wood_elves", "SUBCULTURE", "wef_spellweaver", "Spellweaver"},
        {"wh_dlc05_sc_wef_wood_elves", "SUBCULTURE", "wef_shadowdancer", "Shadowdancer"},

        {"wh_main_sc_grn_greenskins", "SUBCULTURE", "grn_savage_orc_warboss", "Savage Orc Warboss"},
        {"wh_main_sc_grn_greenskins", "SUBCULTURE", "grn_savage_orc_shaman", "Savage Orc Shaman"},
        {"wh_main_sc_grn_greenskins", "SUBCULTURE", "grn_orc_great_shaman", "Orc Great Shaman"},

        {"wh_main_sc_grn_savage_orcs", "SUBCULTURE", "grn_savage_orc_warboss", "Savage Orc Warboss"},
        {"wh_main_sc_grn_savage_orcs", "SUBCULTURE", "grn_savage_orc_shaman", "Savage Orc Great Shaman"},

        {"wh_main_sc_dwf_dwarfs", "SUBCULTURE", "dwf_giant_slayer", "Dragon Slayer"},

        {"wh_main_sc_emp_empire", "SUBCULTURE", "emp_wizard_lord_beasts", "Amber Wizard Lord"},
        {"wh_main_sc_emp_empire", "SUBCULTURE", "emp_wizard_lord_light", "Light Wizard Lord"},
        {"wh_main_sc_emp_empire", "SUBCULTURE", "emp_wizard_lord_fire", "Bright Wizard Lord"},
        {"wh_main_sc_emp_empire", "SUBCULTURE", "emp_wizard_lord_heavens", "Celestial Wizard Lord"},
        {"wh_main_sc_emp_empire", "SUBCULTURE", "emp_wizard_lord_shadow", "Grey Wizard Lord"},
        {"wh_main_emp_wissenland", "FACTION", "emp_wizard_lord_death", "Amethyst Wizard Lord"},
        {"wh2_dlc13_emp_golden_order", "FACTION", "emp_wizard_lord_metal", "Gold Wizard Lord"},
        {"wh_main_sc_emp_empire", "SUBCULTURE", "emp_wizard_metal", "Gold Wizard"},

        {"wh_dlc03_sc_bst_beastmen", "SUBCULTURE", "bst_doombull", "Doombull"},
        
        {"wh2_dlc09_sc_tmb_tomb_kings", "SUBCULTURE", "tmb_liche_high_priest_shadow", "Liche High Priest (Shadows)"},
        {"wh2_dlc09_sc_tmb_tomb_kings", "SUBCULTURE", "tmb_liche_high_priest_death", "Liche High Priest (Death)"},
        {"wh2_dlc09_sc_tmb_tomb_kings", "SUBCULTURE", "tmb_liche_high_priest_light", "Liche High Priest (Light)"},
        {"wh2_dlc09_sc_tmb_tomb_kings", "SUBCULTURE", "tmb_liche_high_priest_nehekhara", "Liche High Priest (Nehekhara)"},

        {"wh_main_sc_chs_chaos", "SUBCULTURE", "chs_shaggoth_champion", "Shaggoth Champion"},

        {"wh_main_sc_nor_norsca", "SUBCULTURE", "nor_fimir_warlord", "Fimir Warlord"},
        {"wh_main_sc_nor_norsca", "SUBCULTURE", "nor_shaman_sorcerer_lord_death", "Shaman-Sorcerer Lord (Death)"},
        {"wh_main_sc_nor_norsca", "SUBCULTURE", "nor_shaman_sorcerer_lord_fire", "Shaman-Sorcerer Lord (Fire)"},
        {"wh_main_sc_nor_norsca", "SUBCULTURE", "nor_shaman_sorcerer_lord_metal", "Shaman-Sorcerer Lord (Metal)"}
    }
}


lord_type_art = {
    SCHEMA = {"lord_type", "art_set_id", "culture", "portrait_name"},
    KEY = {"lord_type", "LIST"},
    DATA = {
        {"wef_darkweaver", "wh2_main_art_set_wef_darkweaver_1", "mixus_lords", "wef_darkweaver_1"},
        {"wef_darkweaver", "wh2_main_art_set_wef_darkweaver_2", "mixus_lords", "wef_darkweaver_2"},
        {"wef_darkweaver", "wh2_main_art_set_wef_darkweaver_3", "mixus_lords", "wef_darkweaver_3"},

        {"wef_highweaver", "wh2_main_art_set_wef_highweaver_1", "mixus_lords", "wef_highweaver_1"},
        {"wef_highweaver", "wh2_main_art_set_wef_highweaver_2", "mixus_lords", "wef_highweaver_2"},
        {"wef_highweaver", "wh2_main_art_set_wef_highweaver_3", "mixus_lords", "wef_highweaver_3"},

        {"wef_spellweaver", "wh2_main_art_set_wef_spellweaver_1", "mixus_lords", "wef_spellweaver_1"},
        {"wef_spellweaver", "wh2_main_art_set_wef_spellweaver_2", "mixus_lords", "wef_spellweaver_2"},
        {"wef_spellweaver", "wh2_main_art_set_wef_spellweaver_3", "mixus_lords", "wef_spellweaver_3"},

        {"wef_shadowdancer", "wh2_main_art_set_wef_shadowdancer_1", "mixus_lords", "wef_shadowdancer_1"},
        {"wef_shadowdancer", "wh2_main_art_set_wef_shadowdancer_2", "mixus_lords", "wef_shadowdancer_2"},
        {"wef_shadowdancer", "wh2_main_art_set_wef_shadowdancer_3", "mixus_lords", "wef_shadowdancer_3"},
        {"wef_shadowdancer", "wh2_main_art_set_wef_shadowdancer_4", "mixus_lords", "wef_shadowdancer_4"},
        {"wef_shadowdancer", "wh2_main_art_set_wef_shadowdancer_5", "mixus_lords", "wef_shadowdancer_5"},

        {"dwf_giant_slayer", "wh2_main_art_set_dwf_giant_slayer_1", "mixus_lords", "dwf_giant_slayer_1"},
        {"dwf_giant_slayer", "wh2_main_art_set_dwf_giant_slayer_2", "mixus_lords", "dwf_giant_slayer_2"},
        {"dwf_giant_slayer", "wh2_main_art_set_dwf_giant_slayer_3", "mixus_lords", "dwf_giant_slayer_3"},
        {"dwf_giant_slayer", "wh2_main_art_set_dwf_giant_slayer_4", "mixus_lords", "dwf_giant_slayer_4"},

        {"bst_doombull", "wh2_main_art_set_bst_doombull_1", "mixus_lords", "bst_doombull_1"},
        {"bst_doombull", "wh2_main_art_set_bst_doombull_2", "mixus_lords", "bst_doombull_2"},
        {"bst_doombull", "wh2_main_art_set_bst_doombull_3", "mixus_lords", "bst_doombull_3"},

        {"chs_shaggoth_champion", "wh2_main_art_set_chs_shaggoth_champion_1", "mixus_lords", "chs_shaggoth_champion_1"},
        {"chs_shaggoth_champion", "wh2_main_art_set_chs_shaggoth_champion_2", "mixus_lords", "chs_shaggoth_champion_2"},
        {"chs_shaggoth_champion", "wh2_main_art_set_chs_shaggoth_champion_3", "mixus_lords", "chs_shaggoth_champion_3"},

        {"grn_savage_orc_warboss", "wh2_main_art_set_grn_savage_orc_warboss_1", "mixus_lords", "grn_savage_orc_warboss_1"},
        {"grn_savage_orc_warboss", "wh2_main_art_set_grn_savage_orc_warboss_2", "mixus_lords", "grn_savage_orc_warboss_2"},
        {"grn_savage_orc_warboss", "wh2_main_art_set_grn_savage_orc_warboss_3", "mixus_lords", "grn_savage_orc_warboss_3"},

        {"emp_wizard_lord_fire", "wh2_main_art_set_emp_wizard_lord_fire_1", "wh_main_emp_empire", "emp_wizard_fire_campaign_01_0"},
        {"emp_wizard_lord_fire", "wh2_main_art_set_emp_wizard_lord_fire_2", "wh_main_emp_empire", "emp_wizard_fire_campaign_02_0"},
        {"emp_wizard_lord_fire", "wh2_main_art_set_emp_wizard_lord_fire_3", "wh_main_emp_empire", "emp_wizard_fire_campaign_03_0"},

        {"emp_wizard_lord_light", "wh2_main_art_set_emp_wizard_lord_light_1", "mixus_lords", "emp_wizard_lord_light_1"},
        {"emp_wizard_lord_light", "wh2_main_art_set_emp_wizard_lord_light_2", "mixus_lords", "emp_wizard_lord_light_2"},
        {"emp_wizard_lord_light", "wh2_main_art_set_emp_wizard_lord_light_3", "mixus_lords", "emp_wizard_lord_light_3"},
        
        {"emp_wizard_metal", "wh2_main_art_set_emp_wizard_metal_1", "mixus_lords", "emp_wizard_metal_1"},
        {"emp_wizard_metal", "wh2_main_art_set_emp_wizard_metal_2", "mixus_lords", "emp_wizard_metal_2"},
        {"emp_wizard_metal", "mixu_art_set_emp_wizard_metal_3", "mixus_lords", "emp_wizard_metal_3"},

        {"emp_wizard_lord_beasts", "wh2_main_art_set_emp_wizard_lord_beasts_1", "mixus_lords", "emp_wizard_lord_beasts_1"},
        {"emp_wizard_lord_beasts", "wh2_main_art_set_emp_wizard_lord_beasts_2", "mixus_lords", "emp_wizard_lord_beasts_2"},

        {"grn_savage_orc_shaman", "wh2_main_art_set_grn_savage_orc_shaman_1", "mixus_lords", "grn_savage_orc_shaman_1"},
        {"grn_savage_orc_shaman", "wh2_main_art_set_grn_savage_orc_shaman_2", "mixus_lords", "grn_savage_orc_shaman_2"},
        {"grn_savage_orc_shaman", "wh2_main_art_set_grn_savage_orc_shaman_3", "mixus_lords", "grn_savage_orc_shaman_3"},
        {"grn_savage_orc_shaman", "wh2_main_art_set_grn_savage_orc_shaman_4", "mixus_lords", "grn_savage_orc_shaman_4"},

        {"grn_orc_great_shaman", "wh2_main_art_set_grn_orc_great_shaman_1", "mixus_lords", "grn_orc_great_shaman_1"},
        {"grn_orc_great_shaman", "wh2_main_art_set_grn_orc_great_shaman_2", "mixus_lords", "grn_orc_great_shaman_2"},
        {"grn_orc_great_shaman", "wh2_main_art_set_grn_orc_great_shaman_3", "mixus_lords", "grn_orc_great_shaman_3"},
        {"grn_orc_great_shaman", "wh2_main_art_set_grn_orc_great_shaman_4", "mixus_lords", "grn_orc_great_shaman_4"},

        {"tmb_liche_high_priest_shadow", "mixu_art_set_tmb_liche_high_priest_shadow_1", "mixus_lords", "tmb_liche_high_priest_04"},
        {"tmb_liche_high_priest_shadow", "mixu_art_set_tmb_liche_high_priest_shadow_2", "mixus_lords", "tmb_liche_high_priest_02"},
        {"tmb_liche_high_priest_shadow", "mixu_art_set_tmb_liche_high_priest_shadow_3", "mixus_lords", "tmb_liche_high_priest_03"},
        {"tmb_liche_high_priest_shadow", "mixu_art_set_tmb_liche_high_priest_shadow_4", "mixus_lords", "tmb_liche_high_priest_01"},

        {"tmb_liche_high_priest_death", "mixu_art_set_tmb_liche_high_priest_death_1", "mixus_lords", "tmb_liche_high_priest_01"},
        {"tmb_liche_high_priest_death", "mixu_art_set_tmb_liche_high_priest_death_2", "mixus_lords", "tmb_liche_high_priest_02"},
        {"tmb_liche_high_priest_death", "mixu_art_set_tmb_liche_high_priest_death_3", "mixus_lords", "tmb_liche_high_priest_03"},
        {"tmb_liche_high_priest_death", "mixu_art_set_tmb_liche_high_priest_death_4", "mixus_lords", "tmb_liche_high_priest_04"},

        {"tmb_liche_high_priest_light", "mixu_art_set_tmb_liche_high_priest_light_1", "mixus_lords", "tmb_liche_high_priest_03"},
        {"tmb_liche_high_priest_light", "mixu_art_set_tmb_liche_high_priest_light_2", "mixus_lords", "tmb_liche_high_priest_04"},
        {"tmb_liche_high_priest_light", "mixu_art_set_tmb_liche_high_priest_light_3", "mixus_lords", "tmb_liche_high_priest_01"},
        {"tmb_liche_high_priest_light", "mixu_art_set_tmb_liche_high_priest_light_4", "mixus_lords", "tmb_liche_high_priest_02"},

        {"tmb_liche_high_priest_nehekhara", "mixu_art_set_tmb_liche_high_priest_nehekhara_1", "mixus_lords", "tmb_liche_high_priest_02"},
        {"tmb_liche_high_priest_nehekhara", "mixu_art_set_tmb_liche_high_priest_nehekhara_2", "mixus_lords", "tmb_liche_high_priest_03"},
        {"tmb_liche_high_priest_nehekhara", "mixu_art_set_tmb_liche_high_priest_nehekhara_3", "mixus_lords", "tmb_liche_high_priest_01"},
        {"tmb_liche_high_priest_nehekhara", "mixu_art_set_tmb_liche_high_priest_nehekhara_4", "mixus_lords", "tmb_liche_high_priest_04"},

        {"nor_fimir_warlord", "wh2_main_art_set_nor_fimir_warlord_1", "mixus_lords", "nor_fimir_warlord_1"},
        {"nor_fimir_warlord", "wh2_main_art_set_nor_fimir_warlord_2", "mixus_lords", "nor_fimir_warlord_2"},
        {"nor_fimir_warlord", "wh2_main_art_set_nor_fimir_warlord_3", "mixus_lords", "nor_fimir_warlord_3"},
        {"nor_fimir_warlord", "wh2_main_art_set_nor_fimir_warlord_4", "mixus_lords", "nor_fimir_warlord_4"},

        {"nor_shaman_sorcerer_lord_death", "wh2_main_art_set_nor_shaman_sorcerer_lord_death_1", "mixus_lords", "nor_shaman_sorcerer_lord_1"},
        {"nor_shaman_sorcerer_lord_death", "wh2_main_art_set_nor_shaman_sorcerer_lord_death_2", "mixus_lords", "nor_shaman_sorcerer_lord_2"},
        {"nor_shaman_sorcerer_lord_death", "wh2_main_art_set_nor_shaman_sorcerer_lord_death_3", "mixus_lords", "nor_shaman_sorcerer_lord_3"},

        {"nor_shaman_sorcerer_lord_metal", "wh2_main_art_set_nor_shaman_sorcerer_lord_metal_1", "mixus_lords", "nor_shaman_sorcerer_lord_2"},
        {"nor_shaman_sorcerer_lord_metal", "wh2_main_art_set_nor_shaman_sorcerer_lord_metal_2", "mixus_lords", "nor_shaman_sorcerer_lord_3"},
        {"nor_shaman_sorcerer_lord_metal", "wh2_main_art_set_nor_shaman_sorcerer_lord_metal_3", "mixus_lords", "nor_shaman_sorcerer_lord_1"},

        {"nor_shaman_sorcerer_lord_fire", "wh2_main_art_set_nor_shaman_sorcerer_lord_fire_1", "mixus_lords", "nor_shaman_sorcerer_lord_3"},
        {"nor_shaman_sorcerer_lord_fire", "wh2_main_art_set_nor_shaman_sorcerer_lord_fire_2", "mixus_lords", "nor_shaman_sorcerer_lord_2"},
        {"nor_shaman_sorcerer_lord_fire", "wh2_main_art_set_nor_shaman_sorcerer_lord_fire_3", "mixus_lords", "nor_shaman_sorcerer_lord_1"}
    }
}

faction_agent_permitted_subtypes_tables = {
    SCHEMA = {"agent", "faction", "subtype"},
    KEY = {"faction", "LIST"},
    DATA = {
        {"wizard", "wh_main_emp_averland", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_empire", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_empire_rebels", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_empire_separatists", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_hochland", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_marienburg", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_marienburg_rebels", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_middenland", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_nordland", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_ostermark", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_ostland", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_stirland", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_talabecland", "emp_wizard_metal"},
        {"wizard", "wh_main_emp_wissenland", "emp_wizard_metal"},
        {"wizard", "wh2_main_emp_sudenburg", "emp_wizard_metal"},
        {"wizard", "wh2_dlc13_emp_golden_order", "emp_wizard_metal"},
        {"wizard", "wh2_dlc13_emp_the_huntmarshals_expedition", "emp_wizard_metal"},
        {"general", "wh2_dlc13_wef_laurelorn_forest", "wef_darkweaver"},
        {"general", "wh_dlc05_wef_argwylon", "wef_darkweaver"},
        {"general", "wh_dlc05_wef_torgovann", "wef_darkweaver"},
        {"general", "wh_dlc05_wef_wood_elves", "wef_darkweaver"},
        {"general", "wh_dlc05_wef_wood_elves_rebels", "wef_darkweaver"},
        {"general", "wh_dlc05_wef_wydrioth", "wef_darkweaver"},
        {"general", "wh2_main_wef_bowmen_of_oreon", "wef_darkweaver"},
        {"general", "wh2_dlc13_wef_laurelorn_forest", "wef_highweaver"},
        {"general", "wh_dlc05_wef_argwylon", "wef_highweaver"},
        {"general", "wh_dlc05_wef_torgovann", "wef_highweaver"},
        {"general", "wh_dlc05_wef_wood_elves", "wef_highweaver"},
        {"general", "wh_dlc05_wef_wood_elves_rebels", "wef_highweaver"},
        {"general", "wh_dlc05_wef_wydrioth", "wef_highweaver"},
        {"general", "wh2_main_wef_bowmen_of_oreon", "wef_highweaver"},
        {"general", "wh2_dlc13_wef_laurelorn_forest", "wef_spellweaver"},
        {"general", "wh_dlc05_wef_argwylon", "wef_spellweaver"},
        {"general", "wh_dlc05_wef_torgovann", "wef_spellweaver"},
        {"general", "wh_dlc05_wef_wood_elves", "wef_spellweaver"},
        {"general", "wh_dlc05_wef_wood_elves_rebels", "wef_spellweaver"},
        {"general", "wh_dlc05_wef_wydrioth", "wef_spellweaver"},
        {"general", "wh2_main_wef_bowmen_of_oreon", "wef_spellweaver"},
        {"dignitary", "wh2_dlc13_wef_laurelorn_forest", "wef_shadowdancer"},
        {"dignitary", "wh_dlc05_wef_argwylon", "wef_shadowdancer"},
        {"dignitary", "wh_dlc05_wef_torgovann", "wef_shadowdancer"},
        {"dignitary", "wh_dlc05_wef_wood_elves", "wef_shadowdancer"},
        {"dignitary", "wh_dlc05_wef_wood_elves_rebels", "wef_shadowdancer"},
        {"dignitary", "wh_dlc05_wef_wydrioth", "wef_shadowdancer"},
        {"dignitary", "wh2_main_wef_bowmen_of_oreon", "wef_shadowdancer"},
        {"general", "wh_main_emp_averland", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_empire", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_empire_rebels", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_empire_separatists", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_hochland", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_marienburg", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_marienburg_rebels", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_middenland", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_nordland", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_ostermark", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_ostland", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_stirland", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_talabecland", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_wissenland", "emp_wizard_lord_beasts"},
        {"general", "wh2_main_emp_sudenburg", "emp_wizard_lord_beasts"},
        {"general", "wh2_dlc13_emp_golden_order", "emp_wizard_lord_beasts"},
        {"general", "wh2_dlc13_emp_the_huntmarshals_expedition", "emp_wizard_lord_beasts"},
        {"general", "wh_main_emp_averland", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_empire", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_empire_rebels", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_empire_separatists", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_hochland", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_marienburg", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_marienburg_rebels", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_middenland", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_nordland", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_ostermark", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_ostland", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_stirland", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_talabecland", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_wissenland", "emp_wizard_lord_light"},
        {"general", "wh2_main_emp_sudenburg", "emp_wizard_lord_light"},
        {"general", "wh2_dlc13_emp_golden_order", "emp_wizard_lord_light"},
        {"general", "wh2_dlc13_emp_the_huntmarshals_expedition", "emp_wizard_lord_light"},
        {"general", "wh_main_emp_averland", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_empire", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_empire_rebels", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_empire_separatists", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_hochland", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_marienburg", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_marienburg_rebels", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_middenland", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_nordland", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_ostermark", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_ostland", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_stirland", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_talabecland", "emp_wizard_lord_fire"},
        {"general", "wh_main_emp_wissenland", "emp_wizard_lord_fire"},
        {"general", "wh2_main_emp_sudenburg", "emp_wizard_lord_fire"},
        {"general", "wh2_dlc13_emp_golden_order", "emp_wizard_lord_fire"},
        {"general", "wh2_dlc13_emp_the_huntmarshals_expedition", "emp_wizard_lord_fire"},
        {"general", "wh_main_grn_bloody_spearz", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_bloody_spearz_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_broken_nose", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_broken_nose_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_greenskins", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_greenskins_rebels", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_greenskins_rebels_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_greenskins_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_necksnappers", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_necksnappers_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_orcs_of_the_bloody_hand", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_orcs_of_the_bloody_hand_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_red_eye", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_red_eye_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_red_fangs", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_red_fangs_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_scabby_eye", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_scabby_eye_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_skullsmasherz", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_skullsmasherz_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_skull-takerz", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_skull-takerz_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_teef_snatchaz", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_teef_snatchaz_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_top_knotz", "grn_savage_orc_warboss"},
        {"general", "wh_main_grn_top_knotz_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh2_main_grn_arachnos", "grn_savage_orc_warboss"},
        {"general", "wh2_main_grn_arachnos_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh2_main_grn_blue_vipers", "grn_savage_orc_warboss"},
        {"general", "wh2_main_grn_blue_vipers_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh2_dlc12_grn_leaf_cutterz_tribe", "grn_savage_orc_warboss"},
        {"general", "wh2_dlc12_grn_leaf_cutterz_tribe_waaagh", "grn_savage_orc_warboss"},
        {"general", "wh2_dlc12_grn_leaf_cutterz_tribe", "grn_savage_orc_shaman"},
        {"general", "wh2_dlc12_grn_leaf_cutterz_tribe_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_bloody_spearz", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_bloody_spearz_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_broken_nose", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_broken_nose_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_greenskins", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_greenskins_rebels", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_greenskins_rebels_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_greenskins_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_necksnappers", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_necksnappers_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_orcs_of_the_bloody_hand", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_orcs_of_the_bloody_hand_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_red_eye", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_red_eye_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_red_fangs", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_red_fangs_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_scabby_eye", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_scabby_eye_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_skullsmasherz", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_skullsmasherz_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_skull-takerz", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_skull-takerz_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_teef_snatchaz", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_teef_snatchaz_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_top_knotz", "grn_savage_orc_shaman"},
        {"general", "wh_main_grn_top_knotz_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh2_main_grn_arachnos", "grn_savage_orc_shaman"},
        {"general", "wh2_main_grn_arachnos_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh2_main_grn_blue_vipers", "grn_savage_orc_shaman"},
        {"general", "wh2_main_grn_blue_vipers_waaagh", "grn_savage_orc_shaman"},
        {"general", "wh2_dlc12_grn_leaf_cutterz_tribe", "grn_orc_great_shaman"},
        {"general", "wh2_dlc12_grn_leaf_cutterz_tribe_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_bloody_spearz", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_bloody_spearz_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_broken_nose", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_broken_nose_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_greenskins", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_greenskins_rebels", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_greenskins_rebels_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_greenskins_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_necksnappers", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_necksnappers_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_orcs_of_the_bloody_hand", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_orcs_of_the_bloody_hand_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_red_eye", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_red_eye_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_red_fangs", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_red_fangs_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_scabby_eye", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_scabby_eye_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_skullsmasherz", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_skullsmasherz_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_teef_snatchaz", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_teef_snatchaz_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_black_venom", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_black_venom_waaagh", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_crooked_moon", "grn_orc_great_shaman"},
        {"general", "wh_main_grn_crooked_moon_waaagh", "grn_orc_great_shaman"},
        {"general", "wh2_dlc15_grn_bonerattlaz", "grn_orc_great_shaman"},
        {"general", "wh2_dlc15_grn_broken_axe", "grn_orc_great_shaman"},
        {"general", "wh2_dlc15_grn_skull_crag", "grn_orc_great_shaman"},
        {"general", "wh2_dlc15_grn_bonerattlaz", "grn_savage_orc_warboss"},
        {"general", "wh2_dlc15_grn_broken_axe", "grn_savage_orc_warboss"},
        {"general", "wh2_dlc15_grn_skull_crag", "grn_savage_orc_warboss"},
        {"dignitary", "wh_main_dwf_barak_varr", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_dwarf_rebels", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_dwarfs", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_karak_azul", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_karak_hirn", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_karak_izor", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_karak_kadrin", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_karak_norn", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_karak_ziflin", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_kraka_drak", "dwf_giant_slayer"},
        {"dignitary", "wh_main_dwf_zhufbar", "dwf_giant_slayer"},
        {"dignitary", "wh2_main_dwf_greybeards_prospectors", "dwf_giant_slayer"},
        {"general", "wh_dlc03_bst_beastmen", "bst_doombull"},
        {"general", "wh_dlc03_bst_beastmen_chaos", "bst_doombull"},
        {"general", "wh_dlc03_bst_jagged_horn", "bst_doombull"},
        {"general", "wh_dlc03_bst_redhorn", "bst_doombull"},
        {"general", "wh2_main_bst_blooded_axe", "bst_doombull"},
        {"general", "wh2_main_bst_manblight", "bst_doombull"},
        {"general", "wh2_main_bst_ripper_horn", "bst_doombull"},
        {"general", "wh2_main_bst_shadowgor", "bst_doombull"},
        {"general", "wh2_main_bst_skrinderkin", "bst_doombull"},
        {"general", "wh2_main_bst_stone_horn", "bst_doombull"},
        {"general", "wh_main_chs_chaos", "chs_shaggoth_champion"},
        {"general", "wh_dlc08_nor_goromadny_tribe", "nor_fimir_warlord"},
        {"general", "wh_dlc08_nor_helspire_tribe", "nor_fimir_warlord"},
        {"general", "wh_dlc08_nor_naglfarlings", "nor_fimir_warlord"},
        {"general", "wh_dlc08_nor_norsca", "nor_fimir_warlord"},
        {"general", "wh_dlc08_nor_vanaheimlings", "nor_fimir_warlord"},
        {"general", "wh_dlc08_nor_wintertooth", "nor_fimir_warlord"},
        {"general", "wh_main_nor_aesling", "nor_fimir_warlord"},
        {"general", "wh_main_nor_baersonling", "nor_fimir_warlord"},
        {"general", "wh_main_nor_bjornling", "nor_fimir_warlord"},
        {"general", "wh_main_nor_graeling", "nor_fimir_warlord"},
        {"general", "wh_main_nor_norsca_rebels", "nor_fimir_warlord"},
        {"general", "wh_main_nor_norsca_separatists", "nor_fimir_warlord"},
        {"general", "wh_main_nor_norsca_separatists_sorcerer_lord", "nor_fimir_warlord"},
        {"general", "wh_main_nor_sarl", "nor_fimir_warlord"},
        {"general", "wh_main_nor_skaeling", "nor_fimir_warlord"},
        {"general", "wh_main_nor_varg", "nor_fimir_warlord"},
        {"general", "wh2_main_nor_aghol", "nor_fimir_warlord"},
        {"general", "wh2_main_nor_hung_incursion_def", "nor_fimir_warlord"},
        {"general", "wh2_main_nor_hung_incursion_hef", "nor_fimir_warlord"},
        {"general", "wh2_main_nor_hung_incursion_lzd", "nor_fimir_warlord"},
        {"general", "wh2_main_nor_hung_incursion_skv", "nor_fimir_warlord"},
        {"general", "wh2_main_nor_mung", "nor_fimir_warlord"},
        {"general", "wh2_main_nor_skeggi", "nor_fimir_warlord"},
        {"general", "wh_dlc08_nor_goromadny_tribe", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_dlc08_nor_helspire_tribe", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_dlc08_nor_naglfarlings", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_dlc08_nor_norsca", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_dlc08_nor_vanaheimlings", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_dlc08_nor_wintertooth", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_aesling", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_baersonling", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_bjornling", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_graeling", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_norsca_rebels", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_norsca_separatists", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_norsca_separatists_sorcerer_lord", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_sarl", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_skaeling", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_main_nor_varg", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh2_main_nor_aghol", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh2_main_nor_hung_incursion_def", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh2_main_nor_hung_incursion_hef", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh2_main_nor_hung_incursion_lzd", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh2_main_nor_hung_incursion_skv", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh2_main_nor_mung", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh2_main_nor_skeggi", "nor_shaman_sorcerer_lord_death"},
        {"general", "wh_dlc08_nor_goromadny_tribe", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_dlc08_nor_helspire_tribe", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_dlc08_nor_naglfarlings", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_dlc08_nor_norsca", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_dlc08_nor_vanaheimlings", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_dlc08_nor_wintertooth", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_aesling", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_baersonling", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_bjornling", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_graeling", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_norsca_rebels", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_norsca_separatists", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_norsca_separatists_sorcerer_lord", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_sarl", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_skaeling", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_main_nor_varg", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh2_main_nor_aghol", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh2_main_nor_hung_incursion_def", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh2_main_nor_hung_incursion_hef", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh2_main_nor_hung_incursion_lzd", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh2_main_nor_hung_incursion_skv", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh2_main_nor_mung", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh2_main_nor_skeggi", "nor_shaman_sorcerer_lord_fire"},
        {"general", "wh_dlc08_nor_goromadny_tribe", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_dlc08_nor_helspire_tribe", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_dlc08_nor_naglfarlings", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_dlc08_nor_norsca", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_dlc08_nor_vanaheimlings", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_dlc08_nor_wintertooth", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_aesling", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_baersonling", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_bjornling", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_graeling", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_norsca_rebels", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_norsca_separatists", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_norsca_separatists_sorcerer_lord", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_sarl", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_skaeling", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_nor_varg", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh2_main_nor_aghol", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh2_main_nor_hung_incursion_def", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh2_main_nor_hung_incursion_hef", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh2_main_nor_hung_incursion_lzd", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh2_main_nor_hung_incursion_skv", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh2_main_nor_mung", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh2_main_nor_skeggi", "nor_shaman_sorcerer_lord_metal"},
        {"general", "wh_main_emp_averland", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_empire", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_empire_rebels", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_empire_separatists", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_hochland", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_marienburg", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_marienburg_rebels", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_middenland", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_nordland", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_ostermark", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_ostland", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_stirland", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_talabecland", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_wissenland", "emp_wizard_lord_heavens"},
        {"general", "wh2_main_emp_sudenburg", "emp_wizard_lord_heavens"},
        {"general", "wh2_dlc13_emp_golden_order", "emp_wizard_lord_heavens"},
        {"general", "wh2_dlc13_emp_the_huntmarshals_expedition", "emp_wizard_lord_heavens"},
        {"general", "wh_main_emp_averland", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_empire", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_empire_rebels", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_empire_separatists", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_hochland", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_marienburg", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_marienburg_rebels", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_middenland", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_nordland", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_ostermark", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_ostland", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_stirland", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_talabecland", "emp_wizard_lord_shadow"},
        {"general", "wh_main_emp_wissenland", "emp_wizard_lord_shadow"},
        {"general", "wh2_main_emp_sudenburg", "emp_wizard_lord_shadow"},
        {"general", "wh2_dlc13_emp_golden_order", "emp_wizard_lord_shadow"},
        {"general", "wh2_dlc13_emp_the_huntmarshals_expedition", "emp_wizard_lord_shadow"},
        {"general", "wh2_dlc09_tmb_dune_kingdoms", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_exiles_of_nehek", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_followers_of_nagash", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_khemri", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_lybaras", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_numas", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_rakaph_dynasty", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_the_sentinels", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_tomb_kings", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_tomb_kings_rebels", "tmb_liche_high_priest_death"},
        {"general", "wh2_dlc09_tmb_dune_kingdoms", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_exiles_of_nehek", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_followers_of_nagash", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_khemri", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_lybaras", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_numas", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_rakaph_dynasty", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_the_sentinels", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_tomb_kings", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_tomb_kings_rebels", "tmb_liche_high_priest_light"},
        {"general", "wh2_dlc09_tmb_dune_kingdoms", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_exiles_of_nehek", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_followers_of_nagash", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_khemri", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_lybaras", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_numas", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_rakaph_dynasty", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_the_sentinels", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_tomb_kings", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_tomb_kings_rebels", "tmb_liche_high_priest_nehekhara"},
        {"general", "wh2_dlc09_tmb_dune_kingdoms", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc09_tmb_exiles_of_nehek", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc09_tmb_followers_of_nagash", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc09_tmb_khemri", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc09_tmb_lybaras", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc09_tmb_numas", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc09_tmb_rakaph_dynasty", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc09_tmb_the_sentinels", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc09_tmb_tomb_kings", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc09_tmb_tomb_kings_rebels", "tmb_liche_high_priest_shadow"},
        {"general", "wh2_dlc13_emp_golden_order", "emp_wizard_lord_metal"},
        {"general", "wh_main_emp_wissenland", "emp_wizard_lord_death"}
    }
}
agent_subtypes_tables = {
    SCHEMA = {"key", "auto_generate", "is_caster", "small_icon", "associated_unit_override", "audio_voiceover_actor_group", "show_in_ui", "cap", "has_female_name", "can_gain_xp", "loyalty_is_applicable", "contributes_to_agent_cap", "recruitment_category", "magic_lore"},
    KEY = {"key", "UNIQUE"},
    DATA = {
        {"emp_wizard_metal", "true", "true", "ui/campaign ui/agents/wh_main_lore_metal.png", "wh2_mixu_emp_cha_wizard_metal", "wh_dlc05_vo_actor_Empire_JadeWizard", "true", "-1", "false", "true", "true", "true"},
        {"wef_shadowdancer", "true", "true", "ui/campaign ui/agents/wh2_main_def_spy.png", "wh2_mixu_wef_cha_shadowdancer", "wh_dlc05_vo_actor_Wood_Elves_Female_Glade_Lord", "true", "-1", "true", "true", "true", "true"},
        {"emp_wizard_lord_beasts", "false", "true", "UI/Campaign UI/Agents/wh_dlc03_lore_beasts.png", "wh2_mixu_emp_cha_wizard_lord_beasts", "vo_actor_Empire_dlc03_AmberWizard", "true", "-1", "false", "true", "true", "true", "emp_wizard_lord", "wh_dlc03_lore_beasts"},
        {"emp_wizard_lord_light", "false", "true", "ui/campaign ui/agents/wh_main_lore_light.png", "wh2_mixu_emp_cha_wizard_lord_light", "wh_main_vo_actor_Empire_LightWizard", "true", "-1", "false", "true", "true", "true", "emp_wizard_lord", "wh_main_lore_light"},
        {"emp_wizard_lord_fire", "false", "true", "UI/Campaign UI/Agents/wh_main_lore_fire.png", "wh2_mixu_emp_cha_wizard_lord_fire", "wh_main_vo_actor_Empire_BrightWizard", "true", "-1", "false", "true", "true", "true", "emp_wizard_lord", "wh_main_lore_fire"},
        {"grn_savage_orc_warboss", "true", "false", "", "wh2_mixu_grn_cha_savage_orc_warboss", "wh_main_vo_actor_Orc_Warboss", "true", "-1", "false", "true", "true", "true", "grn_orc_war_boss", "mixu_dummy_lore_savage_orc_warboss"},
        {"grn_orc_warboss", "true", "false", "", "wh_main_grn_cha_orc_warboss_0", "wh_main_vo_actor_Orc_Warboss", "true", "-1", "false", "true", "true", "true", "grn_orc_war_boss", "mixu_dummy_lore_orc_warboss"},
        {"grn_savage_orc_shaman", "true", "true", "ui/campaign ui/agents/wh_main_lore_big_waaagh.png", "wh2_mixu_grn_cha_savage_orc_shaman", "wh_main_vo_actor_Orc_Shaman", "true", "-1", "false", "true", "true", "true", "grn_goblin_great_shaman", "mixu_dummy_lore_savage_orc_great_shaman"},
        {"grn_goblin_great_shaman", "true", "true", "ui/campaign ui/agents/wh_main_lore_lil_waaagh.png", "wh_main_grn_cha_goblin_great_shaman_0", "wh_main_vo_actor_Goblin_GreatShaman", "true", "-1", "false", "true", "true", "true", "grn_goblin_great_shaman", "wh_main_lore_lil_waaagh"},
        {"grn_orc_great_shaman", "true", "true", "ui/campaign ui/agents/wh_main_lore_big_waaagh.png", "wh2_mixu_grn_cha_orc_great_shaman", "wh_main_vo_actor_Orc_Shaman", "true", "-1", "false", "true", "true", "true", "grn_goblin_great_shaman", "wh_main_lore_big_waaagh"},
        {"dwf_giant_slayer", "true", "false", "ui/campaign ui/agents/wh_main_dwf_dignitary.png", "wh2_mixu_dwf_cha_giant_slayer", "wh_main_vo_actor_Dwarf_Thane", "true", "-1", "false", "true", "true", "true"},
        {"bst_doombull", "false", "false", "", "wh2_mixu_bst_cha_doombull", "wh_dlc03_vo_actor_Beastmen_Gorebull", "true", "-1", "false", "true", "true", "true", "bst_doombull"},
        {"wef_darkweaver", "true", "true", "ui/campaign ui/agents/wh2_main_lore_dark_magic.png", "wh2_mixu_wef_cha_darkweaver", "wh_dlc05_vo_actor_Wood_Elves_Spellsinger", "true", "-1", "true", "true", "true", "true", "wef_spellweaver", "mixu_lore_darkweaver"},
        {"wef_highweaver", "true", "true", "ui/campaign ui/agents/wh2_main_lore_high_magic.png", "wh2_mixu_wef_cha_highweaver", "wh_dlc05_vo_actor_Wood_Elves_Spellsinger", "true", "-1", "true", "true", "true", "true", "wef_spellweaver", "mixu_lore_highweaver"},
        {"wef_spellweaver", "true", "true", "UI/Campaign UI/Agents/wh_dlc03_lore_beasts.png", "wh2_mixu_wef_cha_spellweaver_beasts", "wh_dlc05_vo_actor_Wood_Elves_Spellsinger", "true", "-1", "true", "true", "true", "true", "wef_spellweaver", "mixu_lore_spellweaver"},
        {"chs_shaggoth_champion", "false", "false", "", "wh2_mixu_chs_cha_shaggoth_champion", "wh_dlc03_vo_actor_Beastmen_Gorebull", "true", "-1", "false", "true", "true", "true", "chs_shaggoth"},
        {"nor_fimir_warlord", "true", "false", "", "wh2_mixu_nor_cha_fimir_warlord", "wh_dlc08_vo_actor_Norsca_Fimir_Balefiend", "true", "-1", "true", "true", "true", "true", "nor_fimir_warlord"},
        {"nor_shaman_sorcerer_lord_death", "true", "true", "UI/Campaign UI/Agents/wh_main_lore_death.png", "wh2_mixu_nor_cha_shaman_sorcerer_lord_death", "wh_dlc08_vo_actor_Norsca_Shaman_Sorcerer", "true", "-1", "false", "true", "true", "true", "nor_sorcerer_lord", "wh_main_lore_death"},
        {"nor_shaman_sorcerer_lord_fire", "true", "true", "UI/Campaign UI/Agents/wh_main_lore_fire.png", "wh2_mixu_nor_cha_shaman_sorcerer_lord_fire", "wh_dlc08_vo_actor_Norsca_Shaman_Sorcerer", "true", "-1", "false", "true", "true", "true", "nor_sorcerer_lord", "wh_main_lore_fire"},
        {"nor_shaman_sorcerer_lord_metal", "true", "true", "UI/Campaign UI/Agents/wh_main_lore_metal.png", "wh2_mixu_nor_cha_shaman_sorcerer_lord_metal", "wh_dlc08_vo_actor_Norsca_Shaman_Sorcerer", "true", "-1", "false", "true", "true", "true", "nor_sorcerer_lord", "wh_main_lore_metal"},
        {"emp_wizard_lord_shadow", "false", "true", "ui/campaign ui/agents/wh_dlc05_lore_shadow.png", "wh2_mixu_emp_cha_wizard_lord_shadow", "wh_dlc05_vo_actor_Empire_GreyWizard", "true", "-1", "false", "true", "true", "true", "emp_wizard_lord", "wh_dlc05_lore_shadows"},
        {"emp_wizard_lord_heavens", "false", "true", "ui/campaign ui/agents/wh_main_lore_heavens.png", "wh2_mixu_emp_cha_wizard_lord_heavens", "wh_main_vo_actor_Empire_CelestialWizard", "true", "-1", "false", "true", "true", "true", "emp_wizard_lord", "wh_main_lore_heavens"},
        {"tmb_liche_high_priest_death", "true", "true", "UI/Campaign UI/Agents/wh_main_lore_death.png", "mixu_tmb_cha_liche_high_priest_death", "wh2_dlc09_vo_actor_Tomb_Kings_Liche_Priest", "true", "-1", "false", "true", "true", "true", "tmb_liche_high_priest", "wh_main_lore_death"},
        {"tmb_liche_high_priest_light", "true", "true", "ui/campaign ui/agents/wh_main_lore_light.png", "mixu_tmb_cha_liche_high_priest_light", "wh2_dlc09_vo_actor_Tomb_Kings_Liche_Priest", "true", "-1", "false", "true", "true", "true", "tmb_liche_high_priest", "wh_main_lore_light"},
        {"tmb_liche_high_priest_nehekhara", "true", "true", "ui/campaign ui/agents/wh2_dlc09_lore_nehekhara.png", "mixu_tmb_cha_liche_high_priest_nehekhara", "wh2_dlc09_vo_actor_Tomb_Kings_Liche_Priest", "true", "-1", "false", "true", "true", "true", "tmb_liche_high_priest", "wh2_dlc09_lore_nehekhara"},
        {"tmb_liche_high_priest_shadow", "true", "true", "ui/campaign ui/agents/wh_dlc05_lore_shadow.png", "mixu_tmb_cha_liche_high_priest_shadow", "wh2_dlc09_vo_actor_Tomb_Kings_Liche_Priest", "true", "-1", "false", "true", "true", "true", "tmb_liche_high_priest", "wh_dlc05_lore_shadows"},
        {"emp_wizard_lord_metal", "false", "true", "UI/Campaign UI/Agents/wh_main_lore_metal.png", "mixu_emp_cha_wizard_lord_metal", "wh_dlc05_vo_actor_Empire_JadeWizard", "true", "-1", "false", "true", "true", "true", "emp_wizard_lord", "wh_main_lore_metal"},
        {"emp_wizard_lord_death", "false", "true", "UI/Campaign UI/Agents/wh_main_lore_death.png", "mixu_emp_cha_wizard_lord_death", "wh2_pro07_vo_actor_Empire_Amethyst_Wizard", "true", "-1", "false", "true", "true", "true", "emp_wizard_lord", "wh_main_lore_death"}
    }
}